[workspace]
resolver = "2"
members = ["common", "agent", "hub", "hub-admin"]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"
publish = false

[workspace.dependencies]
serde            = { version = "1", features = ["derive"] }
serde_json       = "1"
tokio            = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "fs", "signal", "process", "time", "sync"] }
tracing          = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow           = "1"
thiserror        = "1"
base64           = "0.22"
hmac             = "0.12"
sha2             = "0.10"
rand             = "0.8"
url              = "2"
toml             = "0.8"
uuid             = { version = "1", features = ["v4", "serde"] }
webauthn-rs      = { version = "0.5.5", features = ["danger-allow-state-serialisation", "danger-user-presence-only-security-keys"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"
