#!/usr/bin/env bash
# Install term-agent on this host. Idempotent; refuses to overwrite an
# existing agent.toml unless --force.
set -euo pipefail

usage() {
  cat <<EOF
Usage: $0 --hub HOST:PORT --machine-id ID --psk PSK [options]

Required:
  --hub HOST:PORT          hub's agent_bind, e.g. term.xyz.com:7700
  --machine-id ID          must match a [[machines]] entry on the hub
  --psk PSK                base64 PSK matching the hub config
                           (use --psk-stdin to read from stdin instead)

Optional:
  --psk-stdin              read PSK from stdin instead of --psk
  --tls on|off             default: on   (must match hub)
  --server-name HOST       cert verify target (default: host part of --hub)
  --shell PATH             default: /bin/bash
  --tmux PATH              default: /usr/bin/tmux

  --user UNIX_USER         run agent as this user; sets a systemd drop-in
                           (default: keep User= from the unit, i.e. root)

  --build-dir DIR          where target/release lives (default: ./target/release)
  --unit-src FILE          systemd unit source        (default: ./systemd/term-agent.service)

  --bin-dir DIR            install binary here      (default: /usr/local/bin)
  --config-dir DIR         agent config dir         (default: /etc/term-agent)

  --no-enable              don't enable/start the unit
  --force                  overwrite an existing agent.toml
  -h, --help
EOF
}

HUB=""
MACHINE_ID=""
PSK=""
PSK_STDIN=false
TLS="on"
SERVER_NAME=""
SHELL_BIN="/bin/bash"
TMUX_BIN="/usr/bin/tmux"
RUN_USER=""

BUILD_DIR="./target/release"
UNIT_SRC="./systemd/term-agent.service"

BIN_DIR="/usr/local/bin"
CONFIG_DIR="/etc/term-agent"

NO_ENABLE=false
FORCE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --hub)         HUB="$2";          shift 2 ;;
    --machine-id)  MACHINE_ID="$2";   shift 2 ;;
    --psk)         PSK="$2";          shift 2 ;;
    --psk-stdin)   PSK_STDIN=true;    shift   ;;
    --tls)         TLS="$2";          shift 2 ;;
    --server-name) SERVER_NAME="$2";  shift 2 ;;
    --shell)       SHELL_BIN="$2";    shift 2 ;;
    --tmux)        TMUX_BIN="$2";     shift 2 ;;
    --user)        RUN_USER="$2";     shift 2 ;;
    --build-dir)   BUILD_DIR="$2";    shift 2 ;;
    --unit-src)    UNIT_SRC="$2";     shift 2 ;;
    --bin-dir)     BIN_DIR="$2";      shift 2 ;;
    --config-dir)  CONFIG_DIR="$2";   shift 2 ;;
    --no-enable)   NO_ENABLE=true;    shift   ;;
    --force)       FORCE=true;        shift   ;;
    -h|--help)     usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

die()  { echo "install-agent: error: $*" >&2; exit 1; }
note() { echo "install-agent: $*"; }

if $PSK_STDIN; then
  PSK="$(cat)"
  PSK="${PSK//$'\n'/}"
fi

[[ -n "$HUB"        ]] || die "--hub is required"
[[ -n "$MACHINE_ID" ]] || die "--machine-id is required"
[[ -n "$PSK"        ]] || die "--psk (or --psk-stdin) is required"
[[ "$TLS" == "on" || "$TLS" == "off" ]] || die "--tls must be on or off"
[[ "$MACHINE_ID" =~ ^[A-Za-z0-9_-]{1,32}$ ]] || die "machine-id must match [A-Za-z0-9_-]{1,32}"

[[ "$(id -u)" -eq 0 ]] || die "must run as root (try: sudo $0 ...)"
[[ -x "$BUILD_DIR/term-agent" ]] || die "missing $BUILD_DIR/term-agent (run: cargo build --release)"
[[ -f "$UNIT_SRC"             ]] || die "missing $UNIT_SRC (systemd unit)"

if [[ -n "$RUN_USER" ]] && ! id "$RUN_USER" >/dev/null 2>&1; then
  die "user $RUN_USER does not exist; create it first"
fi

# tmux sanity
if [[ ! -x "$TMUX_BIN" ]]; then
  if command -v tmux >/dev/null 2>&1; then
    TMUX_BIN="$(command -v tmux)"
    note "using tmux at $TMUX_BIN"
  else
    die "tmux not found at $TMUX_BIN; install it (apt install tmux / dnf install tmux)"
  fi
fi

# --- binary
note "installing binary -> $BIN_DIR/term-agent"
install -m 755 "$BUILD_DIR/term-agent" "$BIN_DIR/"

# --- config dir
mkdir -p "$CONFIG_DIR"
chmod 0750 "$CONFIG_DIR"
if [[ -n "$RUN_USER" ]]; then
  # The agent (running as RUN_USER) needs to be able to enter the dir
  # and read agent.toml; nobody else needs to.
  chown -R "$RUN_USER:$RUN_USER" "$CONFIG_DIR"
fi

# --- agent.toml
CONFIG_PATH="$CONFIG_DIR/agent.toml"
if [[ -e "$CONFIG_PATH" ]] && ! $FORCE; then
  note "$CONFIG_PATH exists; not overwriting (use --force to replace)"
else
  note "writing $CONFIG_PATH"
  server_name_line=""
  [[ -n "$SERVER_NAME" ]] && server_name_line="server_name = \"$SERVER_NAME\""
  cat > "$CONFIG_PATH" <<EOF
## generated by scripts/install-agent.sh on $(date -Is)
hub         = "$HUB"
machine_id  = "$MACHINE_ID"
psk         = "$PSK"
tls         = "$TLS"
$server_name_line
shell       = "$SHELL_BIN"
tmux        = "$TMUX_BIN"
EOF
  sed -i '/^$/N;/^\n$/D' "$CONFIG_PATH"
  if [[ -n "$RUN_USER" ]]; then
    chown "$RUN_USER:$RUN_USER" "$CONFIG_PATH"
  fi
  chmod 0600 "$CONFIG_PATH"
fi

# --- systemd unit + optional user drop-in
note "installing systemd unit"
install -m 644 "$UNIT_SRC" /etc/systemd/system/term-agent.service

DROP_IN_DIR=/etc/systemd/system/term-agent.service.d
if [[ -n "$RUN_USER" ]]; then
  mkdir -p "$DROP_IN_DIR"
  cat > "$DROP_IN_DIR/user.conf" <<EOF
[Service]
User=$RUN_USER
Group=$RUN_USER
EOF
  note "agent will run as $RUN_USER (via drop-in $DROP_IN_DIR/user.conf)"
else
  rm -f "$DROP_IN_DIR/user.conf"
fi

systemctl daemon-reload
if ! $NO_ENABLE; then
  note "enabling + (re)starting term-agent.service"
  systemctl enable term-agent.service
  systemctl restart term-agent.service
  sleep 1
  systemctl --no-pager --full status term-agent.service | head -15 || true
fi

note "done."
cat <<EOF

next:
  - tail logs:  sudo journalctl -fu term-agent.service
  - on the hub, you should see:
      agent registered machine=$MACHINE_ID peer=...
EOF
